version: '3.9'

networks:
  kong-net:
    external: true
    name: kong_kong-net

services:
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx1024m
      - discovery.type=single-node
    networks:
      kong-net:
        ipv4_address: 172.1.1.21

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    networks:
      kong-net:
        ipv4_address: 172.1.1.22

  logstash:
    image: logstash:8.11.3
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5555:5555/udp"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - "./logstash/:/usr/share/logstash/pipeline/"
    environment:
      - MONITORING_ENABLED=false
    networks:
      kong-net:
        ipv4_address: 172.1.1.23