version: '3.9'
services:
  kong_database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    container_name:
      kong_database
    networks:
      - kong-net
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - kong-net
    depends_on:
      - kong_database
  kong_gateway:
    image: kong:3.6
    container_name: kong_gateway
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8443:8443
      - 8444:8444
      - 8445:8445
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database # docker container name
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://0.0.0.0:8002

    command: sh -c "kong migrations bootstrap && kong start"
    networks:
      - kong-net
    depends_on:
      - kong_database
  konga_web:
    image: pantsel/konga
    container_name: konga_web
    ports:
      - 1337:1337
    networks:
      - kong-net
    environment:
      NODE_ENV: development
      TOKEN_SECRET: secret
    depends_on:
      - kong_database
      - kong_gateway
#  zipkin:
#    image: openzipkin/zipkin:latest
#    container_name: zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - kong-net
#  elasticsearch:
#    image: elasticsearch:8.12.0
#    container_name: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      - kong-net
#    environment:
#      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
#      discovery.type: single-node
#  logstash:
#    image: logstash:8.12.0
#    container_name: logstash
#    ports:
#      - 5555:5555/udp
#      - 5044:5044
#      - 9600:9600
#    networks:
#      - kong-net
#    depends_on:
#      - elasticsearch
#  kibana:
#    image: kibana:8.12.0
#    container_name: kibana
#    ports:
#      - 5601:5601
#    networks:
#      - kong-net
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - 9090:9090
#    networks:
#      - kong-net
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    networks:
#      - kong-net
networks:
  kong-net:
    name: kong-net
    driver: bridge
